### ISSUE TITLE
Melhorar flags de pilar

### ISSUE THREAD

**Issue by brunapereira** [brunapereira/pdev#1]
Hoje, as flags de pilar são descritas da seguinte forma:
`-p 2` `-pillar 3`
A ideia é que o pilar por si só seja uma flag.
Exemplo: `-p2  --pillar 2`

**Comment by vitorsgomes** [comment]
Não é possível por um problema com a lib utilizada para criar os comandos. Só são aceitos shortcuts parâmetros de uma letra. Ao tentar colocar -p2 a lib entende que p é um parâmetro e 2 é outro, exibindo um erro de que não é esperando um parâmetro chamado -2.
